org: mjack
app: amplifybranchtest
service: amplifyproject
frameworkVersion: "3"

provider:
  name: aws
  runtime: nodejs18.x

functions:
  function1:
    handler: index.handler

package:
  exclude:
    - node_modules/**
